import { RecoilProvider } from "@/client/Provider/RecoilProvider";
import { Providers } from "@/client/providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <RecoilProvider>{children}</RecoilProvider>
        </Providers>
      </body>
    </html>
  );
}
